### ISSUE TITLE
libpython3.5.so

### ISSUE THREAD

**Issue by gregn610** [mbaltrusitis/dockerfile-centos-python#1]
hi
using pyinstaller inside a mbaltrusitis/centos-python:3.5 container causes this error:

    line 626, in _check_python_library
        raise IOError(msg)
    OSError: Python library not found: libpython3.5mu.so.1.0, libpython3.5m.so.1.0, libpython3.5.so.1.0
    This would mean your Python installation doesn't come with proper library files.
    This usually happens by missing development package, or unsuitable build parameters of Python installation.
    * On Debian/Ubuntu, you would need to install Python development packages
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin).

I think this travis issue could be related and helpful:
    https://github.com/travis-ci/travis-ci/issues/4834

Many thanks

**Comment by mbaltrusitis** [comment]
@gregn610 
This looks to be resolved. Please confirm by checking out #2, give it a whirl and let me know.

**Comment by gregn610** [comment]
That worked a treat! Thank you.
